import os

import gmsh
import numpy as np
from dolfinx.fem import Function
from dolfinx.io import gmshio
from dolfinx.mesh import Mesh
from mpi4py import MPI
from petsc4py import PETSc

from src.boundaryCondition import BoundaryCondition
from src.geom.tree.tree_model import VascularTree
from src.geom.tree.vascusynth_wrapper import generate_vascusynth_tree
from src.scenario import Scenario

# Edit parameters in stenosis_with_tree_params.py (no heavy deps, safe to
# import from bare-metal scripts like vascusynth_pretree.sh).
from src.scenarios.stenosis_with_tree_params import (  # noqa: E402
    TREE_N_TERMINAL, TREE_VOLUME_ML, TREE_Q_IN, TREE_PERF_PRESSURE,
    TREE_TERM_PRESSURE, TREE_MURRAY_EXPONENT, TREE_LAMBDA, TREE_MU_VS,
    TREE_MIN_DISTANCE, TREE_CLOSEST_NEIGHBOURS, TREE_RANDOM_SEED,
    TREE_VESSEL_LOSS_FACTOR, TREE_TMP_DIR,
    TREE_COORD_SCALE, TREE_COUPLING_SLOPE,
)


class StenosisWithTreeSimulation(Scenario):
    """2-D stenosis scenario with a VascuSynth vascular tree at the outlet.

    Geometry
    --------
    x ∈ [0, L]
        Stenosis channel identical to StenosisSimulation (Bézier walls).

    x ∈ [L - TREE_OVERLAP, L + tree_x_extent]
        Planar vascular tree generated by VascuSynth and projected onto the
        XY-plane (Z coordinate discarded).  Each branch is a 2-D rectangular
        strip of half-width = scaled_radius swept along the straight
        centreline segment (VascuSynth edges are straight lines between
        nodes).  All strips are fused into a single surface via OCC Boolean
        operations and merged with the stenosis surface.

    Boundary markers
    ----------------
    fluid_marker  = 1  (surface / volume)
    inlet_marker  = 2  (left face of stenosis at x = 0)
    outlet_marker = 3  (end faces of all terminal tree branches)
    wall_marker   = 4  (all remaining boundary curves)

    Stenosis grades
    ---------------
    "mild"     : severity=0.25, slope=0.3
    "moderate" : severity=0.50, slope=0.5
    "severe"   : severity=0.75, slope=0.3  (default)
    """

    fluid_marker = 1
    inlet_marker = 2
    outlet_marker = 3
    wall_marker = 4

    stenosis_grades = {
        "mild": {"severity": 0.25, "slope": 0.3},
        "moderate": {"severity": 0.50, "slope": 0.5},
        "severe": {"severity": 0.75, "slope": 0.3, "L": 0.05},
    }

    def __init__(
        self,
        solver_name,
        dt,
        T,
        f: tuple[float, float] = (0, 0),
        grade="severe",
        inlet_max_velocity=1.5,
        *,
        rho=1.0,
        mu=3.3e-6,
        **kwargs,
    ):
        self._mesh: Mesh = None
        self._ft = None
        self.inlet_max_velocity = float(inlet_max_velocity)

        # Build mesh option dict from defaults + grade overrides + user kwargs
        self.mesh_options = kwargs.copy()
        defaults = {"L": 0.03, "H": 0.003, "res": 0.0001, "x_position_stenosis": 0.01}
        for k, v in defaults.items():
            if k not in self.mesh_options:
                self.mesh_options[k] = v

        grade_params = self.stenosis_grades.get(grade, self.stenosis_grades["severe"])
        for k, v in grade_params.items():
            if k not in kwargs:
                self.mesh_options[k] = v

        self._bcu: list[BoundaryCondition] = None
        self._bcp: list[BoundaryCondition] = None
        super().__init__(solver_name, "stenosis_with_tree", rho, mu, dt, T, f)

        self.mesh.topology.create_connectivity(
            self.mesh.topology.dim - 1, self.mesh.topology.dim
        )
        self.setup()

    # ── lazy properties ────────────────────────────────────────────────────────

    @property
    def mesh(self):
        if not self._mesh:
            self._mesh, self._ft = self.generate_mesh(**self.mesh_options)
        return self._mesh

    @property
    def bcu(self):
        if not self._bcu:
            fdim = self.mesh.topology.dim - 1
            H = self.mesh_options.get("H", 0.003)

            u_inlet = Function(self.solver.V)
            u_inlet.interpolate(self.inlet_velocity(self.inlet_max_velocity, H))
            bcu_inflow = BoundaryCondition(u_inlet)
            bcu_inflow.initTopological(fdim, self._ft.find(self.inlet_marker))

            u_noslip = Function(self.solver.V)
            u_noslip.x.array[:] = 0
            bcu_walls = BoundaryCondition(u_noslip)
            bcu_walls.initTopological(fdim, self._ft.find(self.wall_marker))

            self._bcu = [bcu_inflow, bcu_walls]
        return self._bcu

    @property
    def bcp(self):
        if not self._bcp:
            fdim = self.mesh.topology.dim - 1
            pr = Function(self.solver.Q)
            pr.x.array[:] = 0
            bc_outflow = BoundaryCondition(pr)
            bc_outflow.initTopological(fdim, self._ft.find(self.outlet_marker))
            self._bcp = [bc_outflow]
        return self._bcp

    def initial_velocity(self, x):
        values = np.zeros((self.mesh.geometry.dim, x.shape[1]), dtype=PETSc.ScalarType)
        return values

    def solve(self, output_folder, afterStepCallback=None):
        return super().solve(output_folder, afterStepCallback)

    # ── mesh generation ────────────────────────────────────────────────────────

    def generate_mesh(self, **kwargs):
        L = kwargs.get("L", 0.03)
        H = kwargs.get("H", 0.003)
        res = kwargs.get("res", 0.0001)
        x_position = kwargs.get("x_position_stenosis", 0.01)
        severity = kwargs.get("severity", 0.75)
        slope = kwargs.get("slope", 0.3)
        tension = kwargs.get("tension", 0.5)

        gdim = 2
        mesh_comm = MPI.COMM_WORLD
        model_rank = 0

        # ── 1. VascuSynth tree generation (rank 0 only) ────────────────────────
        nodes_m: dict = {}
        terminal_pos_m: dict = {}
        edges_scaled: list = []
        r_root: float = 0.0
        coupling_length: float = 0.0
        node_types: dict = {}
        root_id: str = ""

        if mesh_comm.rank == model_rank:
            os.makedirs(os.path.join(TREE_TMP_DIR, "output"), exist_ok=True)

            vs_params = {
                "n_terminal": TREE_N_TERMINAL,
                "tree_volume": TREE_VOLUME_ML,
                "q_in": TREE_Q_IN,
                "perf_pressure": TREE_PERF_PRESSURE,
                "term_pressure": TREE_TERM_PRESSURE,
                "murray_exponent": TREE_MURRAY_EXPONENT,
                "lambda": TREE_LAMBDA,
                "mu_vs": TREE_MU_VS,
                "min_distance": TREE_MIN_DISTANCE,
                "closest_neighbours": TREE_CLOSEST_NEIGHBOURS,
                "random_seed": TREE_RANDOM_SEED,
                "vessel_loss_factor": TREE_VESSEL_LOSS_FACTOR,
                "mu": 3.5e-3,  # blood viscosity (Pa·s)
            }
            gxl_path = generate_vascusynth_tree(vs_params, TREE_TMP_DIR)

            # ── 2. Parse tree and apply modifications ──────────────────────────
            tree = VascularTree.from_xml(gxl_path, vs_params)
            tree.apply_modifications()

            nodes_3d = tree.nodes  # node_id -> np.array([x, y, z]) mm
            node_types = tree.node_types
            raw_edges = [(e["from"], e["to"], e["radius"]) for e in tree.edges]

            # ── 3. Project to 2D: drop Z ───────────────────────────────────────
            nodes_2d = {
                nid: np.array([pos[0], pos[1]]) for nid, pos in nodes_3d.items()
            }

            root_id = next(nid for nid, t in node_types.items() if " root node " in t)
            terminal_ids = [
                nid for nid, t in node_types.items() if " terminal node " in t
            ]

            # Translate so the tree root sits at the origin
            root_mm = nodes_2d[root_id].copy()
            nodes_2d = {nid: pos - root_mm for nid, pos in nodes_2d.items()}

            # ── 4. Scale: fit tree Y-extent to artery height H ────────────────
            all_y = np.array([p[1] for p in nodes_2d.values()])
            y_range_mm = max(all_y.max() - all_y.min(), 1e-9)

            if TREE_COORD_SCALE is None:
                # uniform scale so the projected Y-span equals H
                scale = H / (y_range_mm * 1e-3)
            else:
                scale = TREE_COORD_SCALE

            # Target root radius = 90 % of the stenosis throat half-width
            # throat half-width = H/2 * (1 - severity)
            r_throat = (H / 2.0) * (1.0 - severity)
            r_target_root = 0.9 * r_throat

            # Derive radius_scale so that r_to_m(root_raw_r) == r_target_root
            root_raw_r = next(r for _, __, r in raw_edges if _ == root_id)
            radius_scale = r_target_root / max(root_raw_r * 1e-3 * scale, 1e-12)

            def r_to_m(r_mm: float) -> float:
                return r_mm * 1e-3 * scale * radius_scale

            r_root = r_to_m(root_raw_r)

            # coupling_length: slope = (H/2 - r_root) / coupling_length
            coupling_length = (H / 2.0 - r_root) / TREE_COUPLING_SLOPE

            # Tree root sits at the coupling exit
            origin = np.array([L + coupling_length, H / 2.0])

            def to_m(pos_mm: np.ndarray) -> np.ndarray:
                return pos_mm * 1e-3 * scale + origin

            nodes_m = {nid: to_m(p) for nid, p in nodes_2d.items()}
            terminal_pos_m = {nid: nodes_m[nid] for nid in terminal_ids}
            edges_scaled = [(frm, to, r_to_m(r_mm)) for frm, to, r_mm in raw_edges]

        # ── 5. Build gmsh geometry ─────────────────────────────────────────────
        gmsh.initialize()

        if mesh_comm.rank == model_rank:

            # ── 5a. Stenosis surface (Bézier walls) ───────────────────────────
            h_sten = severity * H / 2.0
            if h_sten >= H / 2.0:
                raise ValueError("stenosis severity must be strictly < 1")

            dist_x = h_sten / slope if slope > 0 else L / 4.0
            dist_x = max(dist_x, L * 0.05)
            dist_x = min(dist_x, min(x_position, L - x_position) * 0.95)

            cp1_x = x_position - dist_x
            cp2_x = x_position + dist_x
            ha = tension * dist_x
            hb = tension * dist_x

            # Corner points
            p_bl = gmsh.model.occ.addPoint(0, 0, 0)
            p_tl = gmsh.model.occ.addPoint(0, H, 0)
            p_tr = gmsh.model.occ.addPoint(L, H, 0)
            p_br = gmsh.model.occ.addPoint(L, 0, 0)

            # Stenosis interpolation points
            p_bot_cp1 = gmsh.model.occ.addPoint(cp1_x, 0, 0)
            p_bot_mid = gmsh.model.occ.addPoint(x_position, h_sten, 0)
            p_bot_cp2 = gmsh.model.occ.addPoint(cp2_x, 0, 0)
            p_top_cp1 = gmsh.model.occ.addPoint(cp1_x, H, 0)
            p_top_mid = gmsh.model.occ.addPoint(x_position, H - h_sten, 0)
            p_top_cp2 = gmsh.model.occ.addPoint(cp2_x, H, 0)

            # Bézier tangent handles
            pb_r1 = gmsh.model.occ.addPoint(cp2_x - ha, 0, 0)
            pb_r2 = gmsh.model.occ.addPoint(x_position + hb, h_sten, 0)
            pb_l1 = gmsh.model.occ.addPoint(x_position - hb, h_sten, 0)
            pb_l2 = gmsh.model.occ.addPoint(cp1_x + ha, 0, 0)
            pt_l1 = gmsh.model.occ.addPoint(cp1_x + ha, H, 0)
            pt_l2 = gmsh.model.occ.addPoint(x_position - hb, H - h_sten, 0)
            pt_r1 = gmsh.model.occ.addPoint(x_position + hb, H - h_sten, 0)
            pt_r2 = gmsh.model.occ.addPoint(cp2_x - ha, H, 0)

            l_inlet = gmsh.model.occ.addLine(p_bl, p_tl)
            l_top_pre = gmsh.model.occ.addLine(p_tl, p_top_cp1)
            l_top_pst = gmsh.model.occ.addLine(p_top_cp2, p_tr)
            l_outlet = gmsh.model.occ.addLine(p_tr, p_br)
            l_bot_pre = gmsh.model.occ.addLine(p_br, p_bot_cp2)
            l_bot_pst = gmsh.model.occ.addLine(p_bot_cp1, p_bl)

            bez_top1 = gmsh.model.occ.addBezier([p_top_cp1, pt_l1, pt_l2, p_top_mid])
            bez_top2 = gmsh.model.occ.addBezier([p_top_mid, pt_r1, pt_r2, p_top_cp2])
            bez_bot1 = gmsh.model.occ.addBezier([p_bot_cp2, pb_r1, pb_r2, p_bot_mid])
            bez_bot2 = gmsh.model.occ.addBezier([p_bot_mid, pb_l1, pb_l2, p_bot_cp1])

            s_loop = gmsh.model.occ.addCurveLoop(
                [
                    l_inlet,
                    l_top_pre,
                    bez_top1,
                    bez_top2,
                    l_top_pst,
                    l_outlet,
                    l_bot_pre,
                    bez_bot1,
                    bez_bot2,
                    l_bot_pst,
                ]
            )
            steno_surf = gmsh.model.occ.addPlaneSurface([s_loop])

            # ── 5b. Coupling trapezoid ────────────────────────────────────────
            # 2-D analogue of the lofted truncated cone in src/geom/coupling.py.
            # Transitions from the full artery outlet (width H at x=L) down to
            # the tree root channel (width 2*r_root at x=L+coupling_length).
            # slope = (H/2 - r_root) / coupling_length  (same convention as stenosis slope)
            p_cp_bl = gmsh.model.occ.addPoint(L,                    0,                  0)
            p_cp_tl = gmsh.model.occ.addPoint(L,                    H,                  0)
            p_cp_tr = gmsh.model.occ.addPoint(L + coupling_length,  H / 2.0 + r_root,   0)
            p_cp_br = gmsh.model.occ.addPoint(L + coupling_length,  H / 2.0 - r_root,   0)

            l_cp_left  = gmsh.model.occ.addLine(p_cp_bl, p_cp_tl)
            l_cp_top   = gmsh.model.occ.addLine(p_cp_tl, p_cp_tr)
            l_cp_right = gmsh.model.occ.addLine(p_cp_tr, p_cp_br)
            l_cp_bot   = gmsh.model.occ.addLine(p_cp_br, p_cp_bl)

            cp_loop = gmsh.model.occ.addCurveLoop([l_cp_left, l_cp_top, l_cp_right, l_cp_bot])
            coupling_surf = gmsh.model.occ.addPlaneSurface([cp_loop])

            # ── 5c. Tree channel surfaces (cubic Bézier splines) ─────────────
            # Mirrors graph_to_mesh.py: each branch is a spline whose start
            # tangent equals the parent's travel direction so that the child
            # "enters" the parent branch smoothly before curving away.
            # The 2D channel is built by sampling the Bézier and offsetting
            # ±r perpendicular to the tangent at each sample point.

            # -- BFS to assign a parent-direction to every node ---------------
            adj_out: dict = {}
            for f, t, _ in edges_scaled:
                adj_out.setdefault(f, []).append(t)

            parent_dir: dict = {}  # node_id -> unit np.array([dx, dy])
            # Root: parent direction is the coupling exit direction (+x)
            parent_dir[root_id] = np.array([1.0, 0.0])
            queue = [root_id]
            visited_bfs = {root_id}
            while queue:
                curr = queue.pop(0)
                for child in adj_out.get(curr, []):
                    if child in visited_bfs:
                        continue
                    visited_bfs.add(child)
                    seg = nodes_m[child] - nodes_m[curr]
                    norm = np.linalg.norm(seg)
                    parent_dir[child] = (
                        seg / norm if norm > 1e-10
                        else parent_dir.get(curr, np.array([1.0, 0.0]))
                    )
                    queue.append(child)

            # -- Helper: sample a cubic Bézier and build offset polygon -------
            N_SAMPLES = 12    # points along the centreline
            HANDLE    = 0.4   # control-point offset as fraction of seg length

            def bezier_channel(A, B, tang_in, r):
                """Closed polygon CCW around the Bézier channel from A to B."""
                seg = B - A
                seg_len = np.linalg.norm(seg)
                if seg_len < 1e-10:
                    return []
                tang_out = seg / seg_len
                h  = seg_len * HANDLE
                p0 = A;            p1 = A + h * tang_in
                p3 = B;            p2 = B - h * tang_out
                top, bot = [], []
                for i in range(N_SAMPLES + 1):
                    t  = i / N_SAMPLES
                    mt = 1.0 - t
                    pt  = mt**3*p0 + 3*mt**2*t*p1 + 3*mt*t**2*p2 + t**3*p3
                    tan = 3*mt**2*(p1-p0) + 6*mt*t*(p2-p1) + 3*t**2*(p3-p2)
                    n_t = np.linalg.norm(tan)
                    if n_t < 1e-12:
                        continue
                    perp = np.array([-tan[1], tan[0]]) / n_t
                    top.append(pt + r * perp)
                    bot.append(pt - r * perp)
                return top + bot[::-1]   # closed CCW polygon

            # -- Build one surface per branch ---------------------------------
            tree_surf_dimtags = []
            for frm, to, r in edges_scaled:
                if frm not in nodes_m or to not in nodes_m:
                    continue
                if r < res * 0.1:
                    continue
                poly = bezier_channel(
                    nodes_m[frm], nodes_m[to],
                    parent_dir.get(frm, np.array([1.0, 0.0])),
                    r,
                )
                if len(poly) < 3:
                    continue
                ptags = [gmsh.model.occ.addPoint(p[0], p[1], 0) for p in poly]
                ltags = [
                    gmsh.model.occ.addLine(ptags[i], ptags[(i + 1) % len(ptags)])
                    for i in range(len(ptags))
                ]
                tloop = gmsh.model.occ.addCurveLoop(ltags)
                tsurf = gmsh.model.occ.addPlaneSurface([tloop])
                tree_surf_dimtags.append((2, tsurf))


            # ── 5d. Boolean fuse: stenosis + coupling + tree channels ─────────
            tools = [(2, coupling_surf)] + tree_surf_dimtags
            gmsh.model.occ.fuse(
                [(2, steno_surf)],
                tools,
                removeObject=True,
                removeTool=True,
            )

            gmsh.model.occ.synchronize()

        # ── 6. Physical groups ─────────────────────────────────────────────────
        inflow, outflow, walls = [], [], []
        if mesh_comm.rank == model_rank:
            all_surfs = gmsh.model.getEntities(dim=gdim)
            gmsh.model.addPhysicalGroup(
                gdim, [s[1] for s in all_surfs], self.fluid_marker
            )
            gmsh.model.setPhysicalName(gdim, self.fluid_marker, "Fluid")

            boundaries = gmsh.model.getBoundary(all_surfs, oriented=False)

            # Build list of (curve_tag, center_of_mass_2d) for classification
            curve_com = []
            for bnd in boundaries:
                com = gmsh.model.occ.getCenterOfMass(bnd[0], bnd[1])
                curve_com.append((bnd[1], np.array([com[0], com[1]])))

            inlet_tol = res * 5.0  # tolerance for x ≈ 0 (inlet face)

            # Proximity threshold for terminal outlet detection:
            # use the maximum channel half-width after scaling
            if edges_scaled:
                max_r = max(r for _, _, r in edges_scaled)
            else:
                max_r = res
            outlet_tol = max_r * 3.0

            for ctag, cxy in curve_com:
                if cxy[0] <= inlet_tol:
                    # Inlet: any curve whose x-centre is at (or very near) 0
                    inflow.append(ctag)
                else:
                    # Outlet: curve centre close to a terminal node position
                    is_outlet = any(
                        np.linalg.norm(cxy - t_pos) < outlet_tol
                        for t_pos in terminal_pos_m.values()
                    )
                    (outflow if is_outlet else walls).append(ctag)

            if inflow:
                gmsh.model.addPhysicalGroup(1, inflow, self.inlet_marker)
                gmsh.model.setPhysicalName(1, self.inlet_marker, "Inlet")
            if outflow:
                gmsh.model.addPhysicalGroup(1, outflow, self.outlet_marker)
                gmsh.model.setPhysicalName(1, self.outlet_marker, "Outlets")
            if walls:
                gmsh.model.addPhysicalGroup(1, walls, self.wall_marker)
                gmsh.model.setPhysicalName(1, self.wall_marker, "Walls")

            if not inflow:
                print("[WARN] No inlet curves detected. Check inlet_tol or geometry.")
            if not outflow:
                print(
                    "[WARN] No outlet curves detected. Check outlet_tol or terminal node positions."
                )

        # ── 7. Mesh ────────────────────────────────────────────────────────────
        gmsh.option.setNumber("Mesh.CharacteristicLengthMin", res)
        gmsh.option.setNumber("Mesh.CharacteristicLengthMax", res * 1.5)

        if mesh_comm.rank == model_rank:
            gmsh.option.setNumber("Mesh.Algorithm", 8)  # Frontal-Delaunay quads
            gmsh.model.mesh.generate(gdim)
            gmsh.model.mesh.setOrder(1)
            gmsh.model.mesh.optimize("Netgen")

            # Save mesh for debugging (open with Gmsh GUI or ParaView)
            os.makedirs(TREE_TMP_DIR, exist_ok=True)
            debug_msh = os.path.join(TREE_TMP_DIR, "stenosis_with_tree_debug.msh")
            gmsh.write(debug_msh)
            print(f"[DEBUG] Mesh written to {debug_msh}")

        mesh, _, ft = gmshio.model_to_mesh(gmsh.model, mesh_comm, model_rank, gdim=gdim)
        mesh.name = "Grid"
        ft.name = "Facet markers"
        gmsh.finalize()

        return mesh, ft

    # ── static helpers ─────────────────────────────────────────────────────────

    @staticmethod
    def inlet_velocity(v_max, y_max):
        """Parabolic (Poiseuille) inlet velocity profile."""

        def velocity(x):
            values = np.zeros((2, x.shape[1]), dtype=PETSc.ScalarType)
            values[0] = 4.0 * v_max * x[1] * (y_max - x[1]) / (y_max**2)
            return values

        return velocity
